name: kalyani_app
description: "An app for my grandmother to put overlays on pictures."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.4.4
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.1.0
  image: ^4.5.4
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  riverpod_annotation: ^2.6.1
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
